/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CriarPartidaController;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author fabio
 */
public class CriarPartida extends javax.swing.JFrame {

    private final CriarPartidaController controller;
    
    public CriarPartida() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        controller = new CriarPartidaController(this);
        controller.carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblCriarPartida = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        cbTime1 = new javax.swing.JComboBox<>();
        cbTime2 = new javax.swing.JComboBox<>();
        lblJogadoresTime1 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        cbJogadoresTime2 = new javax.swing.JComboBox<>();
        cbJogadoresTime1 = new javax.swing.JComboBox<>();
        btnAddJogador1 = new javax.swing.JButton();
        btnAddJogador2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogadoresTime2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJogadoresTime1 = new javax.swing.JTable();
        btnRemoveJogador1 = new javax.swing.JButton();
        btnRemoveJogador2 = new javax.swing.JButton();
        lblData = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCriarPartida.setBackground(new java.awt.Color(0, 0, 0));
        lblCriarPartida.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblCriarPartida.setForeground(new java.awt.Color(0, 0, 0));
        lblCriarPartida.setText("Criar Nova Partida");

        lblTime2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime2.setText("TIME 2");

        lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime1.setText("TIME 1");

        cbTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTime1ActionPerformed(evt);
            }
        });

        lblJogadoresTime1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblJogadoresTime1.setText("Selecionar jogadores");

        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });

        cbJogadoresTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJogadoresTime1ActionPerformed(evt);
            }
        });

        btnAddJogador1.setText("+");
        btnAddJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogador1ActionPerformed(evt);
            }
        });

        btnAddJogador2.setText("+");
        btnAddJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogador2ActionPerformed(evt);
            }
        });

        tblJogadoresTime2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Numero", "Posição"
            }
        ));
        jScrollPane1.setViewportView(tblJogadoresTime2);

        tblJogadoresTime1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Numero", "Posição"
            }
        ));
        jScrollPane2.setViewportView(tblJogadoresTime1);

        btnRemoveJogador1.setText("-");
        btnRemoveJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveJogador1ActionPerformed(evt);
            }
        });

        btnRemoveJogador2.setText("-");
        btnRemoveJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveJogador2ActionPerformed(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data: ");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        jFormattedTextField1.setText("dd/mm/aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(cbJogadoresTime2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddJogador2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoveJogador2)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTime1)
                    .addComponent(cbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cbTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTime2)
                        .addGap(160, 160, 160))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(281, 281, 281)
                            .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(73, 73, 73)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(131, 131, 131)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(cbJogadoresTime1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnAddJogador1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnRemoveJogador1)
                            .addGap(319, 319, 319)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(lblJogadoresTime1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblCriarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblCriarPartida)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime1)
                    .addComponent(lblTime2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblJogadoresTime1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJogador1)
                    .addComponent(cbJogadoresTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddJogador2)
                    .addComponent(cbJogadoresTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveJogador1)
                    .addComponent(btnRemoveJogador2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarPartida)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJogadoresTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJogadoresTime1ActionPerformed
        
    }//GEN-LAST:event_cbJogadoresTime1ActionPerformed

    private void btnAddJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogador1ActionPerformed
        controller.adicionarJogadorTimeCasa();
    }//GEN-LAST:event_btnAddJogador1ActionPerformed

    private void cbTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTime1ActionPerformed

    private void btnRemoveJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveJogador1ActionPerformed
        controller.removerJogadorTimeCasa();
    }//GEN-LAST:event_btnRemoveJogador1ActionPerformed

    private void btnAddJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogador2ActionPerformed
        controller.adicionarJogadorTimeVisitante();
    }//GEN-LAST:event_btnAddJogador2ActionPerformed

    private void btnRemoveJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveJogador2ActionPerformed
        controller.removerJogadorTimeVisitante();
    }//GEN-LAST:event_btnRemoveJogador2ActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        controller.iniciarPartida();
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJogador1;
    private javax.swing.JButton btnAddJogador2;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnRemoveJogador1;
    private javax.swing.JButton btnRemoveJogador2;
    private javax.swing.JComboBox<String> cbJogadoresTime1;
    private javax.swing.JComboBox<String> cbJogadoresTime2;
    private javax.swing.JComboBox<String> cbTime1;
    private javax.swing.JComboBox<String> cbTime2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriarPartida;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblJogadoresTime1;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JTable tblJogadoresTime1;
    private javax.swing.JTable tblJogadoresTime2;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbJogadoresTime1() {
        return cbJogadoresTime1;
    }

    public void setCbJogadoresTime1(JComboBox<String> cbJogadoresTime1) {
        this.cbJogadoresTime1 = cbJogadoresTime1;
    }

    public JComboBox<String> getCbJogadoresTime2() {
        return cbJogadoresTime2;
    }

    public void setCbJogadoresTime2(JComboBox<String> cbJogadoresTime2) {
        this.cbJogadoresTime2 = cbJogadoresTime2;
    }

    public JTable getTblJogadoresTime1() {
        return tblJogadoresTime1;
    }

    public void setTblJogadoresTime1(JTable tblJogadoresTime1) {
        this.tblJogadoresTime1 = tblJogadoresTime1;
    }

    public JTable getTblJogadoresTime2() {
        return tblJogadoresTime2;
    }

    public void setTblJogadoresTime2(JTable tblJogadoresTime2) {
        this.tblJogadoresTime2 = tblJogadoresTime2;
    }

    public JComboBox<String> getCbTime1() {
        return cbTime1;
    }

    public void setCbTime1(JComboBox<String> cbTime1) {
        this.cbTime1 = cbTime1;
    }

    public JComboBox<String> getCbTime2() {
        return cbTime2;
    }

    public void setCbTime2(JComboBox<String> cbTime2) {
        this.cbTime2 = cbTime2;
    }
    
    




}
