/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CriarPartidaController;
import Model.JogadorComboboxModel;
import Model.TimeComboboxModel;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author fabio
 */
public class CriarPartidaView extends javax.swing.JFrame {

    public JogadorComboboxModel jogadorComboboxModel;
    public TimeComboboxModel timeComboboxModel;

    private final CriarPartidaController controller;

    public CriarPartidaView() {
        initComponents();
        setSize(790, 610);
        setTitle("Criar partida");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        controller = new CriarPartidaController(this);
        controller.carregarDados();
        jogadorComboboxModel = new JogadorComboboxModel();
        timeComboboxModel = new TimeComboboxModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblCriarPartida = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        cbTime1 = new javax.swing.JComboBox<>();
        cbTime2 = new javax.swing.JComboBox<>();
        lblJogadoresTime1 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        cbJogadoresTime2 = new javax.swing.JComboBox<>();
        cbJogadoresTime1 = new javax.swing.JComboBox<>();
        btnAddJogador1 = new javax.swing.JButton();
        btnAddJogador2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogadoresTime2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJogadoresTime1 = new javax.swing.JTable();
        btnRemoveJogador1 = new javax.swing.JButton();
        btnRemoveJogador2 = new javax.swing.JButton();
        chkTime1 = new javax.swing.JCheckBox();
        chkTime2 = new javax.swing.JCheckBox();
        lblImagem = new javax.swing.JLabel();
        lblImg = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblCriarPartida.setBackground(new java.awt.Color(0, 0, 0));
        lblCriarPartida.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblCriarPartida.setForeground(new java.awt.Color(255, 255, 255));
        lblCriarPartida.setText("Nova partida");
        getContentPane().add(lblCriarPartida);
        lblCriarPartida.setBounds(280, 30, 230, 42);

        lblTime2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime2.setForeground(new java.awt.Color(255, 255, 255));
        lblTime2.setText("TIME 2");
        getContentPane().add(lblTime2);
        lblTime2.setBounds(590, 70, 70, 25);

        lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblTime1.setText("TIME 1");
        getContentPane().add(lblTime1);
        lblTime1.setBounds(80, 70, 80, 25);

        cbTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbTime1);
        cbTime1.setBounds(50, 110, 130, 22);

        getContentPane().add(cbTime2);
        cbTime2.setBounds(550, 110, 130, 22);

        lblJogadoresTime1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblJogadoresTime1.setForeground(new java.awt.Color(255, 255, 255));
        lblJogadoresTime1.setText("Selecionar jogadores");
        getContentPane().add(lblJogadoresTime1);
        lblJogadoresTime1.setBounds(260, 180, 239, 32);

        btnIniciarPartida.setText("Iniciar Partida");
        btnIniciarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciarPartida);
        btnIniciarPartida.setBounds(320, 540, 114, 23);

        getContentPane().add(cbJogadoresTime2);
        cbJogadoresTime2.setBounds(453, 250, 230, 22);

        cbJogadoresTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJogadoresTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(cbJogadoresTime1);
        cbJogadoresTime1.setBounds(30, 250, 210, 22);

        btnAddJogador1.setText("+");
        btnAddJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddJogador1);
        btnAddJogador1.setBounds(250, 250, 30, 23);

        btnAddJogador2.setText("+");
        btnAddJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddJogador2);
        btnAddJogador2.setBounds(690, 250, 30, 23);

        tblJogadoresTime2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jogador", "Numero", "Posição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJogadoresTime2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 300, 289, 210);

        tblJogadoresTime1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Numero", "Posição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblJogadoresTime1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(30, 300, 280, 210);

        btnRemoveJogador1.setText("-");
        btnRemoveJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveJogador1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveJogador1);
        btnRemoveJogador1.setBounds(290, 250, 30, 23);

        btnRemoveJogador2.setText("-");
        btnRemoveJogador2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveJogador2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRemoveJogador2);
        btnRemoveJogador2.setBounds(730, 250, 30, 23);

        chkTime1.setBackground(new java.awt.Color(51, 51, 51));
        chkTime1.setForeground(new java.awt.Color(255, 255, 255));
        chkTime1.setText("Carregar jogadores");
        chkTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTime1ActionPerformed(evt);
            }
        });
        getContentPane().add(chkTime1);
        chkTime1.setBounds(50, 150, 135, 20);

        chkTime2.setBackground(new java.awt.Color(51, 51, 51));
        chkTime2.setForeground(new java.awt.Color(255, 255, 255));
        chkTime2.setText("Carregar jogadores");
        chkTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTime2ActionPerformed(evt);
            }
        });
        getContentPane().add(chkTime2);
        chkTime2.setBounds(550, 150, 133, 20);
        getContentPane().add(lblImagem);
        lblImagem.setBounds(733, 99, 37, 0);

        lblImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\fabio\\Downloads\\imgCampo.jpg")); // NOI18N
        getContentPane().add(lblImg);
        lblImg.setBounds(0, 0, 780, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbJogadoresTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJogadoresTime1ActionPerformed

    }//GEN-LAST:event_cbJogadoresTime1ActionPerformed

    private void btnAddJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogador1ActionPerformed
        controller.adicionarJogadorTimeCasa();
    }//GEN-LAST:event_btnAddJogador1ActionPerformed

    private void cbTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTime1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTime1ActionPerformed

    private void btnRemoveJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveJogador1ActionPerformed
        controller.removerJogadorTimeCasa();
    }//GEN-LAST:event_btnRemoveJogador1ActionPerformed

    private void btnAddJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogador2ActionPerformed
        controller.adicionarJogadorTimeVisitante();
    }//GEN-LAST:event_btnAddJogador2ActionPerformed

    private void btnRemoveJogador2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveJogador2ActionPerformed
        controller.removerJogadorTimeVisitante();
    }//GEN-LAST:event_btnRemoveJogador2ActionPerformed

    private void btnIniciarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarPartidaActionPerformed
        controller.iniciarPartida();
    }//GEN-LAST:event_btnIniciarPartidaActionPerformed

    private void chkTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTime1ActionPerformed
        controller.carregarTimeCasa();
    }//GEN-LAST:event_chkTime1ActionPerformed

    private void chkTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTime2ActionPerformed
        controller.carregarTimeVisitante();
    }//GEN-LAST:event_chkTime2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPartidaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarPartidaView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJogador1;
    private javax.swing.JButton btnAddJogador2;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnRemoveJogador1;
    private javax.swing.JButton btnRemoveJogador2;
    private javax.swing.JComboBox<String> cbJogadoresTime1;
    private javax.swing.JComboBox<String> cbJogadoresTime2;
    private javax.swing.JComboBox<String> cbTime1;
    private javax.swing.JComboBox<String> cbTime2;
    private javax.swing.JCheckBox chkTime1;
    private javax.swing.JCheckBox chkTime2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriarPartida;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblJogadoresTime1;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JTable tblJogadoresTime1;
    private javax.swing.JTable tblJogadoresTime2;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbJogadoresTime1() {
        return cbJogadoresTime1;
    }

    public void setCbJogadoresTime1(JComboBox<String> cbJogadoresTime1) {
        this.cbJogadoresTime1 = cbJogadoresTime1;
    }

    public JComboBox<String> getCbJogadoresTime2() {
        return cbJogadoresTime2;
    }

    public void setCbJogadoresTime2(JComboBox<String> cbJogadoresTime2) {
        this.cbJogadoresTime2 = cbJogadoresTime2;
    }

    public JTable getTblJogadoresTime1() {
        return tblJogadoresTime1;
    }

    public void setTblJogadoresTime1(JTable tblJogadoresTime1) {
        this.tblJogadoresTime1 = tblJogadoresTime1;
    }

    public JTable getTblJogadoresTime2() {
        return tblJogadoresTime2;
    }

    public void setTblJogadoresTime2(JTable tblJogadoresTime2) {
        this.tblJogadoresTime2 = tblJogadoresTime2;
    }

    public JComboBox<String> getCbTime1() {
        return cbTime1;
    }

    public void setCbTime1(JComboBox<String> cbTime1) {
        this.cbTime1 = cbTime1;
    }

    public JComboBox<String> getCbTime2() {
        return cbTime2;
    }

    public void setCbTime2(JComboBox<String> cbTime2) {
        this.cbTime2 = cbTime2;
    }

    public JCheckBox getChkTime1() {
        return chkTime1;
    }

    public void setChkTime1(JCheckBox chkTime1) {
        this.chkTime1 = chkTime1;
    }

    public JCheckBox getChkTime2() {
        return chkTime2;
    }

    public void setChkTime2(JCheckBox chkTime2) {
        this.chkTime2 = chkTime2;
    }

}
