/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CriarPartidaController;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author fabio
 */
public class CriarPartida extends javax.swing.JFrame {

    private final CriarPartidaController controller;
    
    public CriarPartida() {
        initComponents();
        setLocationRelativeTo(null);
        controller = new CriarPartidaController(this);
        controller.carregarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        lblCriarPartida = new javax.swing.JLabel();
        lblTime2 = new javax.swing.JLabel();
        lblTime1 = new javax.swing.JLabel();
        cbTime1 = new javax.swing.JComboBox<>();
        cbTime2 = new javax.swing.JComboBox<>();
        lblJogadoresTime1 = new javax.swing.JLabel();
        btnIniciarPartida = new javax.swing.JButton();
        btnCadastrarTime = new javax.swing.JButton();
        cbJogadoresTime2 = new javax.swing.JComboBox<>();
        cbJogadoresTime1 = new javax.swing.JComboBox<>();
        btnAddJogador1 = new javax.swing.JButton();
        btnAddJogador2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogadoresTime2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblJogadoresTime1 = new javax.swing.JTable();
        btnRemoveJogador1 = new javax.swing.JButton();
        btnRemoveJogador2 = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCriarPartida.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCriarPartida.setText("Criar Nova Partida");

        lblTime2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime2.setText("TIME 2");

        lblTime1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTime1.setText("TIME 1");

        cbTime1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flamengo", "Botafogo", "Corinthians", "Vasco", "Palmeiras", "Fluminense", "Internacional" }));

        cbTime2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flamengo", "Botafogo", "Corinthians", "Vasco", "Palmeiras", "Fluminense", "Internacional" }));

        lblJogadoresTime1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblJogadoresTime1.setText("Selecionar jogadores");

        btnIniciarPartida.setText("Iniciar Partida");

        btnCadastrarTime.setText("Cadastrar novo time");
        btnCadastrarTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTimeActionPerformed(evt);
            }
        });

        cbJogadoresTime1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbJogadoresTime1ActionPerformed(evt);
            }
        });

        btnAddJogador1.setText("+");
        btnAddJogador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddJogador1ActionPerformed(evt);
            }
        });

        btnAddJogador2.setText("+");

        tblJogadoresTime2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Numero", "Posição"
            }
        ));
        jScrollPane1.setViewportView(tblJogadoresTime2);

        tblJogadoresTime1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogador", "Numero", "Posição"
            }
        ));
        jScrollPane2.setViewportView(tblJogadoresTime1);

        btnRemoveJogador1.setText("-");

        btnRemoveJogador2.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnIniciarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblCriarPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblTime1)
                        .addGap(299, 299, 299)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(lblTime2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(cbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnCadastrarTime))
                            .addComponent(lblJogadoresTime1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(cbJogadoresTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddJogador2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemoveJogador2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(cbJogadoresTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAddJogador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveJogador1)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(lblCriarPartida)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTime1)
                    .addComponent(lblTime2))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCadastrarTime)))
                .addGap(36, 36, 36)
                .addComponent(lblJogadoresTime1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddJogador1)
                    .addComponent(cbJogadoresTime2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddJogador2)
                    .addComponent(cbJogadoresTime1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemoveJogador1)
                    .addComponent(btnRemoveJogador2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(btnIniciarPartida)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTimeActionPerformed
        CadastrarTime cadastrarTime = new CadastrarTime();
        cadastrarTime.setVisible(true);
    }//GEN-LAST:event_btnCadastrarTimeActionPerformed

    private void cbJogadoresTime1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbJogadoresTime1ActionPerformed
        
    }//GEN-LAST:event_cbJogadoresTime1ActionPerformed

    private void btnAddJogador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddJogador1ActionPerformed
        controller.adicionarJogador();
    }//GEN-LAST:event_btnAddJogador1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CriarPartida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddJogador1;
    private javax.swing.JButton btnAddJogador2;
    private javax.swing.JButton btnCadastrarTime;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnRemoveJogador1;
    private javax.swing.JButton btnRemoveJogador2;
    private javax.swing.JComboBox<String> cbJogadoresTime1;
    private javax.swing.JComboBox<String> cbJogadoresTime2;
    private javax.swing.JComboBox<String> cbTime1;
    private javax.swing.JComboBox<String> cbTime2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCriarPartida;
    private javax.swing.JLabel lblJogadoresTime1;
    private javax.swing.JLabel lblTime1;
    private javax.swing.JLabel lblTime2;
    private javax.swing.JTable tblJogadoresTime1;
    private javax.swing.JTable tblJogadoresTime2;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCbJogadoresTime1() {
        return cbJogadoresTime1;
    }

    public void setCbJogadoresTime1(JComboBox<String> cbJogadoresTime1) {
        this.cbJogadoresTime1 = cbJogadoresTime1;
    }

    public JComboBox<String> getCbJogadoresTime2() {
        return cbJogadoresTime2;
    }

    public void setCbJogadoresTime2(JComboBox<String> cbJogadoresTime2) {
        this.cbJogadoresTime2 = cbJogadoresTime2;
    }

    public JTable getTblJogadoresTime1() {
        return tblJogadoresTime1;
    }

    public void setTblJogadoresTime1(JTable tblJogadoresTime1) {
        this.tblJogadoresTime1 = tblJogadoresTime1;
    }

    public JTable getTblJogadoresTime2() {
        return tblJogadoresTime2;
    }

    public void setTblJogadoresTime2(JTable tblJogadoresTime2) {
        this.tblJogadoresTime2 = tblJogadoresTime2;
    }
    




}
